
export const provider=Symbol("provider")
export const generateObject=Symbol("generateObject")
export const checkValid=Symbol("checkValid")
export const prepareQueue=Symbol("prepareQueue")
export const getName=Symbol("getName")
export const getRef=Symbol("getRef")
export const resourceIdentifier=Symbol("resourceIdentifier")
export const resourceName=Symbol("resourceName")
export const checkCache=Symbol("checkChache")
export const stacktrace=Symbol("stacktrace")
export const s_path=Symbol("path")