import { Aliasable } from "../general";
import { Resource } from "../generatables/resource";
import { getName, s_isAliased } from "../symbols";

/**
 * replaced the autogenerated resource name with a predefined one
 * 
 * this is supposed to be mainly used for migrating from allready defined 
 * templates so that you dont have to recreate tables,gateways or other 
 * resources that should not be recreated
 * @param name the name to use instead of the autogenerated one
 * @param resource the resource to rename
 */
export function Alias<T extends Resource>(name:string,resource:T):T & Aliasable{
    resource[getName]=() => name
    resource[s_isAliased]=true
    return resource as T & Aliasable
}