export const users=new DynamoDb.Table()
    .name("userTable")
    .billingMode("PAY_PER_REQUEST")
    .keys("N","id","HASH")
    .keys("S","username",{
        key:"HASH",
        index:new DynamoDb.Table.LocalIndex()
            .Name("username")
            .ProjectionType("INCLUDE")
            .Attribute("test")
            .Attribute("email")
    })
    .secondaryIndex(new DynamoDb.Table.GlobalIndex()
        .Name("glabol")
        .ProjectionType("ALL")
        .Attribute("randomHash","HASH")
        .capacity(1,1))
    .Capacity(5,2)