
const randomAlias = new Lambda.Alias()
    .Name("nothin")
export const pedro = new Output("out")
    .Value(randomAlias.r)
export const test = new Lambda.Function()
    .Role(new Iam.Role()
        .AssumePolicy(new Iam.Policy.Document()
            .Statement(new Iam.Policy.Statement()
                .Actions("stuff")
                .principals("Service","lambda.amazon.com")))
        .policy("main",new Iam.Policy.Document()
            .Statement(new Iam.Policy.Statement()
                .Actions("dynamodb:getItem")
                .resources("*"))))
    .Code("s3://bucket/key/path:4")
    .Runtime("go1.x")
    .environment("paul", "meier")
    .environment({
        sven: "no",
        "7": "4"
    })
    .version(
        new Lambda.Version()
            .description("paul")
            .alias(new Lambda.Alias()
                .Name("peter")
                .eventMapping(new Lambda.EventMapping()
                    .EventSource("arn:random")))
            .alias(randomAlias),
        new Lambda.Version()
            .description("t1")
            .alias(randomAlias, 23),
        new Lambda.Version()
            .alias(randomAlias, 41)
            .eventMapping(new Lambda.EventMapping()
                .EventSource("somthin"))
    )
    .eventMapping(new Lambda.EventMapping()
        .EventSource("nothin"))
    .permission(new Lambda.Permission()
        .Action("sts:RunShit")
        .Principal("principia"))
    .layer(new Lambda.Layer()
        .Content("s3://random/file")
        .runtimes("dotnetcore2.1", Sub`node10.${Aws.region}`)
        .permission(new Lambda.LayerPermission()
            .Action("inherit:shit")
            .Principal(Sub`peter:${Aws.partition}`)))