export const param1 = new SSM.Parameter()
    .Type("String")
    .Value("this is a test")
    .allowedPattern(/^this.+/)
    .description("a boring old string")
    .name("boringString")
    .policies([
        new SSM.Parameter.Policy.Expiration()
            .Timestamp("2019-02-01"),
        new SSM.Parameter.Policy.ExpirationNotification()
            .Before(4, "Days"),
        new SSM.Parameter.Policy.NoChangeNotification()
            .After(5, "Hours")
    ])
    .tag("paul", "meier")
    .tag({ one: "ichi", two: "ni" })
    .tier("Intelligent-Tiering")
export const param2 = new SSM.Parameter()
    .Type("StringList")
    .Value("one,two,three")
    .policies('{"test":"paul"}')

export const out1=new Output()
    .Value(param1.r)
export const out2=new Output()
    .Value(param1.a.Type)
export const out3=new Output()
    .Value(param1.a.Value)
export const out4=new Output()
    .Value(param1.a.Arn)