export const lower=new SQS.Queue()
    .delaySeconds(-1)
    .kmsMasterKey("paul",59)
    .maximumMessageSize(1023)
    .messageRetentionPeriod(59)
    .receiveMessageWaitTime(-1)
    .visibilityTimeout(-1)
    .policy(new SQS.QueuePolicy())
export const higher=new SQS.Queue()
    .delaySeconds(901)
    .kmsMasterKey("paul",86_401)
    .maximumMessageSize(262_145)
    .messageRetentionPeriod(1_209_601)
    .receiveMessageWaitTime(21)
    .visibilityTimeout(43_200)